Controllers/AboutUsController.cs
namespace oldCapitalWeb.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using oldCapitalWeb.Models;
    using oldCapitalWeb.Services.Home;

    using static ArticleConstants.Constants.AboutUsPageArticles;
    public class AboutUsController : Controller
    {

        public IActionResult Index()
        {
            var articleList = new List<ArticleViewModel>();

            var headArticle = new ArticleViewModel
            {
                Id = FrontEndHeadId,
                Title = HeadTitle,
                Text = HeadArticleText,
            };
            articleList.Add(headArticle);

            var firstArticle = new ArticleViewModel
            {
                Id = FrontEndArticleOneId,
                Title = SecondArticleTitle,
                Text = SecondArticleText,
            };
            articleList.Add(firstArticle);

            var secondArticle = new ArticleViewModel
            {
                Id = FrontEndArticleTwoId,
                Title = ThirdArticleTitle,
                Text = ThirdArticleText,
            };
            articleList.Add(secondArticle);

            return View(articleList);
        }
    }
}

Controllers/ArtistsController.cs
using Microsoft.AspNetCore.Mvc;

namespace oldCapitalWeb.Controllers
{
    public class ArtistsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/ContactUsController.cs
namespace oldCapitalWeb.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    public class ContactUsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/FaQController.cs
namespace oldCapitalWeb.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using oldCapitalWeb.Models;
    using oldCapitalWeb.Services.FaQ;

    public class FaQController : Controller
    {
        private readonly IFaQService faqService;

        public FaQController(IFaQService faqService)
        {
            this.faqService = faqService;
        }

        public async Task<IActionResult> Index()
        {
            var allFaQ = await faqService.GetAllFaQAsync(); 

            return View(allFaQ);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var model = new FaQViewModel();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(FaQViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            await this.faqService.AddFaQAsync(model.Question, model.Answer);

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Edit()
        {
            return View();
        }

        public IActionResult Delete()
        {
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/oldCapitalWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm bg-opacity-75 border-bottom box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Old Capital<br />Tattoo Shop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="AboutUs" asp-action="Index">Aboutp Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="FaQ" asp-action="Index">FaQ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Artists" asp-action="Index">Artists</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Admin
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                                <li><a class="dropdown-item" asp-area="" asp-controller="FaQ" asp-action="Create">Create new FAQ</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Create">Create new Article</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Artists" asp-action="Edit">Edit Profile</a></li>
                            </ul>
                        </li>
                        <li> <a class="nav-link text-white contact-nav" asp-area="" asp-controller="ContactUs" asp-action="Index">Contact Us</a></li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div>
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top bg-opacity-50 footer text-muted">
        <div class="container">
            &copy; @DateTime.UtcNow.Year - PalauzovoInc.
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        $(window).scroll(function () {
            var navbar = $('.navbar');

            if ($(window).scrollTop() > 0) {
                navbar.addClass('fixed');
            } else {
                navbar.removeClass('fixed');
            }
        });</script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>